"""Backend-neutral durable store contract.

The runtime deliberately depends on this small protocol rather than on
SQLite-specific details.  :class:`~src.runtime.sqlite_store.SQLiteStore` is
the first implementation, but keeping the contract here makes a later
PostgreSQL or broker-backed store a replacement instead of a rewrite.

Methods are intentionally typed in terms of ``Any`` at the edges.  Channel
adapters and Agent runtimes have their own immutable envelope classes and the
SQLite adapter already performs the normalization; importing those concrete
types here would re-introduce the coupling this module is meant to prevent.
Implementations should document whether additional methods participate in a
caller-owned transaction.  The public methods below commit their own short
transaction in the SQLite implementation.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class DurableStore(Protocol):
    """Asynchronous persistence boundary used by the task manager/worker."""

    async def initialize(self) -> None: ...

    async def close(self) -> None: ...

    async def accept_inbound(
        self, inbound: Any, *, task: Any | None = None, create_task: bool = True, **kwargs: Any
    ) -> Any: ...

    async def create_task(self, task: Any | None = None, **kwargs: Any) -> Any: ...

    async def get_task(self, task_id: str) -> Any | None: ...

    async def get_execution(self, execution_id: str) -> Any | None: ...

    async def list_task_executions(
        self, task_id: str, *, limit: int = 100, newest_first: bool = False
    ) -> list[Any]: ...

    async def list_tasks(self, *, limit: int = 100, **filters: Any) -> list[Any]: ...

    async def claim_next_task(
        self, worker_id: str, *, lease_seconds: float = 60.0, **kwargs: Any
    ) -> Any | None: ...

    async def mark_task_running(
        self, task_id: str, claim_token: str, **kwargs: Any
    ) -> bool: ...

    async def append_task_event(self, task_id: str, event: Any = None, **kwargs: Any) -> Any: ...

    async def complete_task(self, task_id: str, result: Any = None, **kwargs: Any) -> Any: ...

    async def request_cancel(self, task_id: str, **kwargs: Any) -> bool: ...

    async def retry_task(self, task_id: str, **kwargs: Any) -> Any: ...

    async def begin_command_receipt(self, command_id: str, **kwargs: Any) -> Any: ...

    async def get_command_receipt(self, command_id: str) -> Any | None: ...

    async def reopen_interrupted_command_receipt(
        self, command_id: str, **kwargs: Any
    ) -> Any: ...

    async def complete_command_receipt(self, command_id: str, **kwargs: Any) -> Any: ...

    async def interrupt_command_receipt(self, command_id: str, **kwargs: Any) -> Any: ...

    async def claim_outbox(self, worker_id: str, **kwargs: Any) -> list[Any]: ...

    async def create_user_outbox(self, delivery: Any = None, **kwargs: Any) -> Any: ...

    async def get_outbox_item(self, outbox_id: str) -> Any | None: ...

    async def get_reply_scope(self, reply_scope_id: str) -> Any | None: ...

    async def get_reply_scope_for_inbound(
        self, inbound_message_id: str
    ) -> Any | None: ...

    async def project_reply_candidate(self, **kwargs: Any) -> Any: ...

    async def drain_deferred_replies(self, **kwargs: Any) -> Any: ...

    async def activate_outbox_contextless_variant(
        self, outbox_id: str, claim_token: str | None = None, **kwargs: Any
    ) -> bool: ...

    async def mark_outbox_sent(self, outbox_id: str, **kwargs: Any) -> bool: ...

    async def mark_outbox_failed(self, outbox_id: str, **kwargs: Any) -> bool: ...

    async def create_outgoing_media(self, **kwargs: Any) -> Any: ...

    async def claim_outgoing_media(self, worker_id: str, **kwargs: Any) -> list[Any]: ...

    async def transition_outgoing_media(self, media_id: str, to_state: Any, **kwargs: Any) -> bool: ...

    async def create_transcription_candidate(self, **kwargs: Any) -> Any: ...

    async def get_transcription_candidate(self, confirmation_id: str) -> Any | None: ...

    async def resolve_transcription(self, confirmation_id: str, *, status: str, **kwargs: Any) -> bool: ...

    async def consume_transcription(self, confirmation_id: str, task_id: str) -> bool: ...

    async def retry_outgoing_media(self, media_id: str, **kwargs: Any) -> bool: ...

    async def present_unseen(self, **kwargs: Any) -> list[Any]: ...

    async def claim_mailbox(self, destination_agent_id: str, worker_id: str, **kwargs: Any) -> list[Any]: ...

    async def renew_mailbox_lease(
        self, mailbox_id: str, claim_token: str, **kwargs: Any
    ) -> bool: ...

    async def create_agent_message(self, **kwargs: Any) -> Any: ...

    async def get_route(self, **kwargs: Any) -> str: ...

    async def set_route(self, **kwargs: Any) -> bool: ...

    async def mark_agent_deleted(self, agent_id: str, **kwargs: Any) -> bool: ...

    async def reactivate_agent(self, profile: Any) -> bool: ...

    async def commit_agent_reactivation(self, profile: Any, **kwargs: Any) -> bool: ...

    async def clear_agent_deleted(self, agent_id: str) -> bool: ...

    async def is_agent_deleted(self, agent_id: str) -> bool: ...

    async def put_skill(self, skill: Any, *, agent_id: str = "codex") -> bool: ...

    async def get_skill(
        self, agent_id: str, skill_id: str, version: str | None = None
    ) -> Any | None: ...

    async def list_skills(
        self, *, agent_id: str = "codex", enabled: bool | None = None
    ) -> list[Any]: ...

    async def save_cursor(self, *, channel: str, bot_id: str, cursor: str, **kwargs: Any) -> bool: ...

    async def clear_cursor(self, *, channel: str, bot_id: str, **kwargs: Any) -> bool: ...

    async def get_cursor(self, *, channel: str, bot_id: str) -> str: ...

    async def reconcile(self, **kwargs: Any) -> Any: ...

    async def startup_reconcile(self, **kwargs: Any) -> Any: ...

    async def claim_attachment_cleanup(self, attachment_id: str, **kwargs: Any) -> bool: ...

    async def finish_attachment_cleanup(
        self, attachment_id: str, *, deleted: bool, **kwargs: Any
    ) -> bool: ...


# Names used by integrations written against earlier plan revisions.  They
# intentionally point at the same structural protocol.
Store = DurableStore
StoreProtocol = DurableStore
RuntimeStore = DurableStore


__all__ = ["DurableStore", "RuntimeStore", "Store", "StoreProtocol"]
