"""Channel adapters and channel-neutral envelopes."""

from importlib import import_module

from .models import (
    ChannelCapabilities,
    ChannelCommand,
    ChannelMessage,
    DeliveryPolicy,
    DeliveryReceipt,
    InboundEnvelope,
    InboundMessage,
    LARK_CAPABILITIES,
    LARK_DELIVERY_POLICY,
    NormalizedInbound,
    ReplyTarget,
    UserDelivery,
    WECHAT_CAPABILITIES,
    WECHAT_DELIVERY_POLICY,
    parse_command,
)
from .commands import (
    COMMAND_HELP,
    COMMAND_POLICIES,
    COMMAND_REGISTRY,
    DEFAULT_COMMAND_POLICY,
    DEFERRED_REPLY_QUOTA_CAPABILITY,
    LARK_COMMAND_POLICY,
    MVP_COMMANDS,
    MVP_COMMAND_NAMES,
    MVPCommandRouter,
    WECHAT_COMMAND_POLICY,
    ChannelCommandPolicy,
    CommandRegistryEntry,
    CommandRegistryGroup,
    command_client_id,
    command_delivery_id,
    command_help_for_channel,
    command_initial_reply,
    command_names_for_channel,
    command_policy_for,
    command_request_id,
    command_supported,
    command_task_id,
    filter_command_registry,
    run_shell_command,
    unsupported_command_response,
)


_LAZY_EXPORTS = {
    "LarkAccountState": (".lark", "AccountState"),
    "LarkAccountSupervisor": (".lark", "LarkAccountSupervisor"),
    "LarkAttachmentPromoter": (".lark", "LarkAttachmentPromoter"),
    "LarkBotProfile": (".lark", "LarkBotProfile"),
    "LarkCliProcess": (".lark", "LarkCliProcess"),
    "LarkCommandRouter": (".lark", "LarkCommandRouter"),
    "LarkDeliveryWorker": (".lark", "LarkDeliveryWorker"),
    "LarkGateway": (".lark", "LarkGateway"),
    "LarkMediaDeliveryWorker": (".lark", "LarkMediaDeliveryWorker"),
    "normalize_lark_event": (".lark", "normalize_lark_event"),
    "Acceptance": (".wechat", "Acceptance"),
    "WeChatAdapter": (".wechat", "WeChatAdapter"),
    "WeChatChannelAdapter": (".wechat", "WeChatChannelAdapter"),
    "WeChatDeliveryWorker": (".wechat", "WeChatDeliveryWorker"),
    "WeChatGateway": (".wechat", "WeChatGateway"),
    "WeChatInboundMediaPromoter": (".wechat", "WeChatInboundMediaPromoter"),
    "WeChatMediaDeliveryWorker": (".wechat", "WeChatMediaDeliveryWorker"),
    "WeChatMediaWorker": (".wechat", "WeChatMediaWorker"),
    "WeChatOutboxWorker": (".wechat", "WeChatOutboxWorker"),
    "WechatAdapter": (".wechat", "WechatAdapter"),
    "WechatGateway": (".wechat", "WechatGateway"),
    "conversation_id_for": (".wechat", "conversation_id_for"),
    "external_message_id_for": (".wechat", "external_message_id_for"),
    "extract_text": (".wechat", "extract_text"),
    "make_monitor_handler": (".wechat", "make_monitor_handler"),
    "normalize_message": (".wechat", "normalize_message"),
    "normalize_wechat_message": (".wechat", "normalize_wechat_message"),
    "send_media_delivery": (".wechat", "send_media_delivery"),
    "send_user_delivery": (".wechat", "send_user_delivery"),
    "send_user_delivery_async": (".wechat", "send_user_delivery_async"),
    "send_wechat_delivery": (".wechat", "send_wechat_delivery"),
    "stable_client_id": (".wechat", "stable_client_id"),
}


def __getattr__(name: str):
    """Resolve peer-adapter exports without eagerly importing either wire."""

    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute = target
    value = getattr(import_module(module_name, __name__), attribute)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))

__all__ = [
    "Acceptance",
    "COMMAND_HELP",
    "COMMAND_POLICIES",
    "COMMAND_REGISTRY",
    "DEFAULT_COMMAND_POLICY",
    "DEFERRED_REPLY_QUOTA_CAPABILITY",
    "ChannelCommand",
    "ChannelCapabilities",
    "ChannelMessage",
    "CommandRegistryEntry",
    "CommandRegistryGroup",
    "DeliveryPolicy",
    "DeliveryReceipt",
    "InboundEnvelope",
    "InboundMessage",
    "MVPCommandRouter",
    "MVP_COMMANDS",
    "MVP_COMMAND_NAMES",
    "LARK_COMMAND_POLICY",
    "LARK_CAPABILITIES",
    "LARK_DELIVERY_POLICY",
    "LarkAccountState",
    "LarkAccountSupervisor",
    "LarkAttachmentPromoter",
    "LarkBotProfile",
    "LarkCliProcess",
    "LarkCommandRouter",
    "LarkDeliveryWorker",
    "LarkGateway",
    "LarkMediaDeliveryWorker",
    "NormalizedInbound",
    "ReplyTarget",
    "UserDelivery",
    "WECHAT_CAPABILITIES",
    "WECHAT_DELIVERY_POLICY",
    "WECHAT_COMMAND_POLICY",
    "ChannelCommandPolicy",
    "WeChatAdapter",
    "WeChatChannelAdapter",
    "WeChatDeliveryWorker",
    "WeChatMediaDeliveryWorker",
    "WeChatMediaWorker",
    "WeChatOutboxWorker",
    "WeChatGateway",
    "WeChatInboundMediaPromoter",
    "WechatAdapter",
    "WechatGateway",
    "conversation_id_for",
    "command_client_id",
    "command_delivery_id",
    "command_initial_reply",
    "command_request_id",
    "command_task_id",
    "command_help_for_channel",
    "command_names_for_channel",
    "command_policy_for",
    "command_supported",
    "external_message_id_for",
    "extract_text",
    "filter_command_registry",
    "make_monitor_handler",
    "normalize_message",
    "normalize_lark_event",
    "normalize_wechat_message",
    "parse_command",
    "run_shell_command",
    "send_wechat_delivery",
    "send_media_delivery",
    "send_user_delivery",
    "send_user_delivery_async",
    "stable_client_id",
    "unsupported_command_response",
]
